import fs from 'node:fs';

// Reads env vars (also accepts VITE_-prefixed names) and writes the browser-safe config.js.
// Use `--optional` to keep the existing config.js when no env vars are set.
const env = process.env;
const url = (env.SUPABASE_URL || env.VITE_SUPABASE_URL || '').trim();
const key = (env.SUPABASE_PUBLISHABLE_KEY || env.VITE_SUPABASE_PUBLISHABLE_KEY || env.SUPABASE_ANON_KEY || env.VITE_SUPABASE_ANON_KEY || '').trim();
const optional = process.argv.includes('--optional');

if (!url && !key && optional) {
  console.log('No SUPABASE_* environment variables set; keeping existing config.js.');
  process.exit(0);
}
if (!url || !key) {
  console.error('Missing SUPABASE_URL or SUPABASE_PUBLISHABLE_KEY.');
  process.exit(1);
}
if (/service_role|sb_secret_/i.test(key)) {
  console.error('Refusing to place a secret/service-role key in browser config.');
  process.exit(1);
}
const safe = (v) => v.replace(/\\/g, '\\\\').replace(/'/g, "\\'");
const output = `/* Generated by scripts/generate-config.mjs - browser-safe values only. */\nwindow.APP_CONFIG = {\n  supabaseUrl: '${safe(url)}',\n  supabasePublishableKey: '${safe(key)}'\n};\n`;
fs.writeFileSync('config.js', output);
console.log('config.js generated successfully.');
